2025-05-11 17:10:47,117 ERROR: Problema de codificação ao enviar para ['juninhoboni@gmail.com']. Certifique-se que todos os textos estão em UTF-8. Erro: 'ascii' codec can't encode character '\xe7' in position 815: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:159]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 127, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 172, in send
    return self._attempt_send(recipients, msg_strings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 178, in _attempt_send
    result = self.smtp.sendmail(self.user, recipients, msg_strings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe7' in position 815: ordinal not in range(128)
2025-05-11 17:10:48,755 ERROR: Problema de codificação ao enviar para ['michelepersonalizados2025@gmail.com']. Certifique-se que todos os textos estão em UTF-8. Erro: 'ascii' codec can't encode character '\xe7' in position 816: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:159]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 127, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 172, in send
    return self._attempt_send(recipients, msg_strings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 178, in _attempt_send
    result = self.smtp.sendmail(self.user, recipients, msg_strings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe7' in position 816: ordinal not in range(128)
2025-05-11 17:10:48,995 WARNING: Orçamento 37 salvo, mas emails falharam parcialmente [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:260]
2025-05-11 17:11:15,519 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-2nf9g2v60sb'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'AC'), ('produto', 'caderno'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', ''), ('obs', '')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:185]
2025-05-11 17:11:15,522 WARNING: Campos obrigatórios faltando: ['Estampa'] [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:209]
2025-05-11 17:11:21,670 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-2nf9g2v60sb'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'AC'), ('produto', 'caderno'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa Stitch'), ('obs', '')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:185]
2025-05-11 17:11:21,673 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 17:11:21,712 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 17:12:02,555 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:75]
2025-05-11 17:12:18,850 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-2nf9g2v60sb'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'AC'), ('produto', 'caderno'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa Stitch'), ('obs', '')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:185]
2025-05-11 17:12:18,965 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 17:12:20,050 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 17:12:31,586 ERROR: Problema de codificação ao enviar para ['juninhoboni@gmail.com']. Certifique-se que todos os textos estão em UTF-8. Erro: 'ascii' codec can't encode character '\xe7' in position 815: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:159]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 127, in enviar_email
    yag.send(
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 172, in send
    return self._attempt_send(recipients, msg_strings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\projetointegrador\.venv\Lib\site-packages\yagmail\sender.py", line 178, in _attempt_send
    result = self.smtp.sendmail(self.user, recipients, msg_strings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe7' in position 815: ordinal not in range(128)
2025-05-11 17:15:37,605 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:73]
2025-05-11 17:15:42,672 INFO: Dados recebidos: ImmutableMultiDict([('csrf_token', 'simulated-csrf-token-2nf9g2v60sb'), ('nome', 'Juninho Boni'), ('telefone', '(11) 11111-1111'), ('email', 'juninhoboni@gmail.com'), ('rua', 'Teste'), ('numero', '123'), ('complemento', ''), ('bairro', 'Teste'), ('cep', '14820-480'), ('cidade', 'Americo'), ('uf', 'AC'), ('produto', 'caderno'), ('tipo_caneca', 'simples'), ('cor_caneca', 'amarela'), ('tipo_caderno', 'brochura'), ('quantidade_de_paginas', '50'), ('quantidade', '1'), ('estampa', 'Estampa Stitch'), ('obs', '')]) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:163]
2025-05-11 17:15:42,814 INFO: Validando e-mail: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:51]
2025-05-11 17:15:43,901 INFO: E-mail validado: juninhoboni@gmail.com [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\models.py:54]
2025-05-11 17:16:14,085 ERROR: Erro ao enviar e-mail: 'ascii' codec can't encode character '\xe3' in position 394: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:147]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 126, in enviar_email
    server.sendmail(
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 394: ordinal not in range(128)
2025-05-11 17:16:19,625 ERROR: Erro ao enviar e-mail: 'ascii' codec can't encode character '\xe3' in position 408: ordinal not in range(128) [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:147]
Traceback (most recent call last):
  File "C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py", line 126, in enviar_email
    server.sendmail(
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 864, in sendmail
    msg = _fix_eols(msg).encode('ascii')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 408: ordinal not in range(128)
2025-05-11 17:16:19,662 WARNING: Orçamento 40 salvo, mas emails falharam parcialmente [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:238]
2025-05-11 17:18:31,768 INFO: Aplicação de orçamentos iniciada [in C:\Sites\Micheli-Personalizados-main\Micheli-Personalizados-main\app.py:73]
